services:
  nextcloud-ephemeral-master:
    build:
      context: .
      args:
        BRANCH: master
    ports:
      - "${PORT}:80"
  nextcloud-ephemeral-stable16:
    build:
      context: .
      dockerfile: php7.2.Dockerfile
      args:
        BRANCH: stable16
        BRANCH_MAIN: stable16
    ports:
      - "${PORT}:80"
  nextcloud-ephemeral-stable17:
    build:
      context: .
      dockerfile: php7.2.Dockerfile
      args:
        BRANCH: stable17
        BRANCH_MAIN: stable17
    ports:
      - "${PORT}:80"
  nextcloud-ephemeral-stable18:
    build:
      context: .
      dockerfile: php7.2.Dockerfile
      args:
        BRANCH: stable18
        BRANCH_MAIN: stable18
    ports:
      - "${PORT}:80"
  nextcloud-ephemeral-stable19:
    build:
      context: .
      dockerfile: php7.2.Dockerfile
      args:
        BRANCH: stable19
        BRANCH_MAIN: stable19
    ports:
      - "${PORT}:80"
  nextcloud-ephemeral-stable20:
    build:
      context: .
      dockerfile: php7.4.Dockerfile
      args:
        BRANCH: stable20
        BRANCH_MAIN: stable20
    ports:
      - "${PORT}:80"
  nextcloud-ephemeral-stable21:
    build:
      context: .
      dockerfile: php7.4.Dockerfile
      args:
        BRANCH: stable21
        BRANCH_MAIN: stable21
    ports:
      - "${PORT}:80"
  nextcloud-ephemeral-stable22:
    build:
      context: .
      dockerfile: php7.4.Dockerfile
      args:
        BRANCH: stable22
        BRANCH_MAIN: stable22
    ports:
      - "${PORT}:80"
  nextcloud-ephemeral-stable23:
    build:
      context: .
      dockerfile: php7.4.Dockerfile
      args:
        BRANCH: stable23
        BRANCH_MAIN: stable23
    ports:
      - "${PORT}:80"
  nextcloud-ephemeral-stable24:
    build:
      context: .
      dockerfile: php7.4.Dockerfile
      args:
        BRANCH: stable24
        BRANCH_MAIN: stable24
    ports:
      - "${PORT}:80"
  nextcloud-ephemeral-stable25:
    build:
      context: .
      args:
        BRANCH: stable25
        BRANCH_MAIN: stable25
    ports:
      - "${PORT}:80"
  nextcloud-ephemeral-stable26:
    build:
      context: .
      args:
        BRANCH: stable26
        BRANCH_MAIN: stable26
    ports:
      - "${PORT}:80"
  nextcloud-ephemeral-stable27:
    build:
      context: .
      args:
        BRANCH: stable27
        BRANCH_MAIN: stable27
    ports:
      - "${PORT}:80"

  nextcloud-ephemeral-stable28:
    build:
      context: .
      args:
        BRANCH: stable28
        BRANCH_MAIN: stable28
    ports:
      - "${PORT}:80"

  nextcloud-ephemeral-stable29:
    build:
      context: .
      args:
        BRANCH: stable29
        BRANCH_MAIN: stable29
    ports:
      - "${PORT}:80"

  nextcloud-ephemeral-stable30:
    build:
      context: .
      args:
        BRANCH: stable30
        BRANCH_MAIN: stable30
    ports:
      - "${PORT}:80"

  nextcloud-ephemeral-stable31:
    build:
      context: .
      args:
        BRANCH: stable31
        BRANCH_MAIN: stable31
    ports:
      - "${PORT}:80"

  nextcloud-ephemeral-stable32:
    build:
      context: .
      args:
        BRANCH: stable32
        BRANCH_MAIN: stable32
    ports:
      - "${PORT}:80"

  nextcloud-longlived-stable25:
    build:
      context: .
      args:
        BRANCH: stable25
        BRANCH_MAIN: stable25
    ports:
      - "${PORT}:80"
    restart: always
    volumes:
      - nextcloud-stable:/var/www/html
      - apps-stable:/var/www/html/custom_apps
      - config-stable:/var/www/html/config
      - data-stable:/var/www/html/data
  nextcloud-talk-stable:
    build:
      context: .
      dockerfile: talk.Dockerfile
      args:
        BRANCH: stable25
        BRANCH_MAIN: stable25
    ports:
      - "${PORT}:80"
    volumes:
      - nextcloud-talk:/var/www/html
      - apps-talk:/var/www/html/custom_apps
      - config-talk:/var/www/html/config
      - data-talk:/var/www/html/data
  nextcloud-talk-master:
    build:
      context: .
      dockerfile: talk.Dockerfile
      args:
        BRANCH: master
    ports:
      - "${PORT}:80"

volumes:
  nextcloud-stable:
  apps-stable:
  config-stable:
  data-stable:

  nextcloud-talk:
  apps-talk:
  config-talk:
  data-talk:
